/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#1d17b2',
        'inverse-surface': '#dae2fd',
        'on-background': '#dae2fd',
        'secondary-fixed': '#ffdad8',
        'surface-variant': '#2d3449',
        'surface-bright': '#31394d',
        'on-tertiary-fixed': '#07006c',
        secondary: '#ffb3b0',
        'on-tertiary': '#1000a9',
        'on-error': '#690005',
        'on-secondary': '#670211',
        'on-secondary-fixed-variant': '#881d24',
        'surface-container-lowest': '#060e20',
        'surface-tint': '#4edea3',
        tertiary: '#c0c1ff',
        primary: '#4edea3',
        'tertiary-fixed-dim': '#c0c1ff',
        'secondary-container': '#881d24',
        'primary-container': '#10b981',
        'on-primary-container': '#00422b',
        'inverse-on-surface': '#283044',
        background: '#0b1326',
        'on-secondary-container': '#ff9996',
        'on-error-container': '#ffdad6',
        'surface-container-highest': '#2d3449',
        'inverse-primary': '#006c49',
        'on-primary': '#003824',
        'surface-container': '#171f33',
        'primary-fixed': '#6ffbbe',
        'on-primary-fixed-variant': '#005236',
        'error-container': '#93000a',
        'on-surface-variant': '#bbcabf',
        'surface-container-high': '#222a3d',
        'on-secondary-fixed': '#410006',
        'on-tertiary-fixed-variant': '#2f2ebe',
        error: '#ffb4ab',
        'surface-container-low': '#131b2e',
        'surface-dim': '#0b1326',
        'tertiary-fixed': '#e1e0ff',
        'outline-variant': '#3c4a42',
        surface: '#0b1326',
        'secondary-fixed-dim': '#ffb3b0',
        'on-surface': '#dae2fd',
        'primary-fixed-dim': '#4edea3',
        outline: '#86948a',
        'tertiary-container': '#9699ff',
        'on-primary-fixed': '#002113',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-md': ['"Hanken Grotesk"', 'sans-serif'],
        'label-md': ['Geist', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
